[deps]
Altro = "5dcf52e5-e2fb-48e0-b826-96f46d2e3e73"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RobotDynamics = "38ceca67-d8d3-44e8-9852-78a5596522e1"
RobotZoo = "74be38bb-dcc2-4b9e-baf3-d6373cd95f10"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TrajectoryOptimization = "c79d492b-0548-5874-b488-5a62c1d9d0ca"
